version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root # Corrected user
      - DB_PASSWORD=kmitl_project  # Corrected password
      - DB_NAME=kmitl_project
      - FLASK_DEBUG=1  # 1 for development, 0 for production
      - SECRET_KEY=your_secret_key_here
      - JWT_SECRET_KEY=your_jwt_secret_key_here
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kmitl_project
      MYSQL_DATABASE: kmitl_project
      MYSQL_USER: root
      MYSQL_PASSWORD: kmitl_project
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: